Traceback (most recent call last):
  File "/Users/rahul/Documents/Programming/Automating the Boring Stuff with Python /Debugging/The Raises and Assert Statements.py", line 35, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
